name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (frontend)
        working-directory: ./app/frontend
        run: npm install

      - name: Install dependencies (backend)
        working-directory: ./app/backend
        run: npm install

      - name: Build Docker images with build args
        run: |
          docker build -t stock-frontend ./app/frontend


          docker build -t vanshp17/stock-backend:latest ./app/backend

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push images
        run: |
          docker push vanshp17/stock-frontend:latest
          docker push vanshp17/stock-backend:latest
