name: StockPRO CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1
      ECR_FRONTEND_URI: ${{ secrets.ECR_FRONTEND_URI }}
      ECR_BACKEND_URI: ${{ secrets.ECR_BACKEND_URI }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_FRONTEND_URI
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BACKEND_URI

      - name: Build frontend Docker image
        run: docker build -t ${{ secrets.ECR_FRONTEND_URI }}:latest ./app/frontend

      - name: Trivy scan frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $ECR_FRONTEND_URI:latest
          format: 'table'
          exit-code: '1'

      - name: Push frontend image to ECR
        run: docker push $ECR_FRONTEND_URI:latest

      - name: Build backend Docker image
        run: docker build -t ${{ secrets.ECR_BACKEND_URI }}:latest ./app/backend

      - name: Trivy scan backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $ECR_BACKEND_URI:latest
          format: 'table'
          exit-code: '1'

      - name: Push backend image to ECR
        run: docker push $ECR_BACKEND_URI:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/dops05/app
            docker compose pull
            docker compose up -d --build

      - name: Notify failure via email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "StockPRO CI/CD Pipeline Failed"
          body: "One of the steps failed. Check the Actions logs."
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
