name: StockPRO CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      ECR_FRONTEND_URI: ${{ secrets.ECR_FRONTEND_URI }}
      ECR_BACKEND_URI: ${{ secrets.ECR_BACKEND_URI }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$ECR_FRONTEND_URI"
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$ECR_BACKEND_URI"

    - name: Build Frontend Image
      run: docker build -t "$ECR_FRONTEND_URI:latest" ./app/frontend

    - name: Push Frontend Image to ECR
      run: docker push "$ECR_FRONTEND_URI:latest"

    - name: Build Backend Image
      run: |
        BACKEND_IMAGE=$(echo "$ECR_BACKEND_URI" | tr -d '\r\n')
        echo "Building backend image: $BACKEND_IMAGE:latest"
        docker build -t "$BACKEND_IMAGE:latest" ./app/backend

    - name: Push Backend Image to ECR
      run: |
        BACKEND_IMAGE=$(echo "$ECR_BACKEND_URI" | tr -d '\r\n')
        echo "Pushing backend image: $BACKEND_IMAGE:latest"
        docker push "$BACKEND_IMAGE:latest"

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.67.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

    - name: Trivy Scan Frontend
      run: trivy image --exit-code 1 --severity HIGH,CRITICAL "$ECR_FRONTEND_URI:latest"

    - name: Trivy Scan Backend
      env:
        TRIVY_DISABLE_VEX_NOTICE: true
      run: |
        BACKEND_IMAGE=$(echo "$ECR_BACKEND_URI" | tr -d '\r\n')
        echo "Scanning backend image: $BACKEND_IMAGE:latest"
        trivy image --exit-code 1 --severity HIGH,CRITICAL --ignorefile ./app/backend/.trivyignore "$BACKEND_IMAGE:latest"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_PEM }}
        script: |
          cd ~/dops05/app
          docker compose pull
          docker compose up -d --build
